language: node_js
deploy:
  provider: heroku
  app: alchemy-deployment
  api_key:
    secure: BKDniVjYm0BfNB8tMmnAqE3q97eyCylX4AUgdR/WN/NlMfJKwT1YHreCJJ9t5HoTdxPvUYc9Is/q8Yjqxbq8b1Exf08tuZNi0M/PRHrt6/uaFsqKsu5tD1uWiyeHp55ShYQVNqgfcCwUu4xTYDKJD95PsEDGRx1ghwfa4zzlfTup3XAt7aqiRH+zvZNp2kp2V78Jb93dp9hsm9AS4L+482U/mkvZaCk0AOOSPfem1hszcE57twCSTUPn3QF2JqORIB6HqCvMIepwTdaJE/+S9dHtJ/tLxPFUT5zFPdlaccOpqi8Q0GN4Jt5UZ7N8mI9J837KfrMoIg6jLQKVwMH4NP32ZwlpsHFdmoPbKxRNOQzz9gdvL4iaGK0I2OzpiUSMBj00/QB44y9JD3pi1vzzIAeV8zWuxCPC3EqWiPW6bT3yIOKmE6+8YrHoHOpkfcVwZoBILN3KHPSxCpKsuyziRSqkXrel0KzvGNKXpFXa0QCyfKpfRs83niermN/P3fz+yyyzgdLYifARA8DHNURqKlCXnhvM7/dUeO7QTjjp7q439ZjqsTpBT4oOpKF7mKvYVrX2hmGNGjwY5kdNS1ebt9Px3RdeQKlH3dehRUY1b2sx5DiXGzkNCFJuorK3wfiQzhZbKDKsecmqSL4Sg9M1szIOfINLerdMritDKoIrE0o=
